version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo Build started on `date`
      - echo Skipping build, serving static HTML
artifacts:
  files:
    - '**/*'
